### ISSUE TITLE
Release 545.29.06

### ISSUE THREAD

**Issue by scaronni** [NVIDIA/nvidia-modprobe#4]
Hello, any chance to have the source code drops for the 545.29.06 for all the open components? Some people are waiting for the backlight fix introduced there.

- nvidia-modprobe
- nvidia-persistenced
- nvidia-settings
- nvidia-xconfig

Thanks & regards.

**Comment by aaronp24** [comment]
Sorry about the delay; I was out of the office and didn't have access to my work accounts. I've pushed the update.
